import { site, projects, activities, directions, learningPaths } from '../content';
import { Link } from '../lib/router';
import { Icon } from '../components/Icon';
import { ProjectCard, ActivityCard } from '../components/Cards';
import { Directions, JoinBanner, SectionTitle } from '../components/UI';
export default function Home() { return <>
  <section className="home-hero"><div className="hero-photo" role="img" aria-label="电路板视觉示意"/><div className="hero-vignette"/><div className="container hero-content"><span className="hero-eyebrow"><i/>{site.school} · 学生技术社区</span><h1>单片机与<br/><span>嵌入式技术协会</span></h1><p className="hero-tagline">{site.tagline}</p><p className="hero-description">{site.description}</p><div className="hero-actions"><Link to="/about" className="button button--primary">了解协会<Icon name="arrow" size={18}/></Link><Link to="/join" className="button button--glass">加入我们<Icon name="diagonal" size={17}/></Link><Link to="/projects" className="hero-text-link">查看项目<Icon name="chevron" size={15}/></Link></div><div className="hero-signature"><span>BUILD. SHARE. GROW.</span><div/><span>MCU / IOT / EDGE AI</span></div></div></section>
  <div className="container stats-wrap"><section className="stats-bar" aria-label="网站内容概览">{[{ icon: 'cpu', value: String(directions.length).padStart(2,'0'), title: '实践方向', text: '从硬件到智能' }, { icon: 'layers', value: String(projects.length).padStart(2,'0'), title: '项目示例', text: '让想法有迹可循' }, { icon: 'book', value: String(learningPaths.length).padStart(2,'0'), title: '学习路径', text: '找到自己的起点' }, { icon: 'users', value: '∞', title: '创意与可能', text: '和同伴一起探索' }].map(s => <div className="stat" key={s.title}><Icon name={s.icon} size={25}/><div><strong>{s.value}</strong><span>{s.title}</span><small>{s.text}</small></div></div>)}</section></div>
  <section className="section home-directions"><div className="container"><SectionTitle centered eyebrow="FIND YOUR DIRECTION" title="从一块开发板，走向更大的世界。" description="找到感兴趣的方向，把知识连成一套真正运行的系统。"/><Directions compact/></div></section>
  <section className="section section--white"><div className="container"><SectionTitle eyebrow="MADE TO WORK" title="让想法，成为看得见的作品。" description="从第一行代码，到最后一次调试。每个项目，都是一次完整的探索。" to="/projects" action="探索全部项目"/><div className="project-grid">{projects.map(p => <ProjectCard key={p.id} project={p}/>)}</div><p className="quiet-note">项目为概念展示示例，正式成果与资料将在核实后更新。</p></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="LIFE IN THE ASSOCIATION" title="不止学习，还有一起做事的日常。" description="动手、交流、分享。在一次次实践中，认识技术，也认识彼此。" to="/activities" action="查看活动"/><div className="activity-grid">{activities.map(a => <ActivityCard key={a.id} activity={a}/>)}</div></div></section>
  <section className="home-manifesto"><div className="container"><span>01 / OUR BELIEF</span><h2>好的想法，<span>值得被做出来。</span></h2><p>保持好奇，认真动手。把经验分享给下一位同行的人。</p><Link className="text-link" to="/about">认识我们的协会<Icon name="arrow" size={18}/></Link></div><svg viewBox="0 0 1440 160" preserveAspectRatio="none" aria-hidden="true"><path d="M0 95Q200 0 420 100T900 105T1440 60V160H0Z" fill="#143145"/><path d="M0 110Q240 30 460 117T960 118T1440 90" fill="none" stroke="#4c96b6" opacity=".45"/></svg></section><JoinBanner/>
</>; }
