import { site, projects, activities, directions } from '../content';
import { Link } from '../lib/router';
import { Icon } from '../components/Icon';
import { ProjectCard, ActivityCard } from '../components/Cards';
import { Directions, JoinBanner, SectionTitle } from '../components/UI';
export default function Home() { return <>
  <section className="home-hero"><div className="hero-photo" role="img" aria-label="嵌入式电路板视觉背景"/><div className="hero-vignette"/><div className="container hero-content"><span className="hero-eyebrow"><i/>{site.school} · {site.college}</span><h1>单片机与<br/><span>嵌入式协会</span></h1><p className="hero-tagline">{site.tagline}</p><p className="hero-description">{site.description}</p><div className="hero-actions"><Link to="/about" className="button button--primary">了解协会<Icon name="arrow" size={18}/></Link><Link to="/join" className="button button--glass">加入我们<Icon name="diagonal" size={17}/></Link><Link to="/projects" className="hero-text-link">查看项目<Icon name="chevron" size={15}/></Link></div><div className="hero-signature"><span>BUILD. SHARE. GROW.</span><div/><span>MCU / IOT / EDGE AI</span></div></div></section>
  <div className="container stats-wrap"><section className="stats-bar" aria-label="协会概览">{[{ icon: 'calendar', value: site.founded, title: '成立年份', text: '从 2024 开始积累' }, { icon: 'layers', value: '501', title: '实践空间', text: site.location }, { icon: 'cpu', value: String(directions.length).padStart(2,'0'), title: '实践方向', text: '从硬件到智能' }, { icon: 'book', value: String(projects.length).padStart(2,'0'), title: '项目记录', text: '持续迭代与分享' }].map(s => <div className="stat" key={s.title}><Icon name={s.icon} size={25}/><div><strong>{s.value}</strong><span>{s.title}</span><small>{s.text}</small></div></div>)}</section></div>
  <section className="section home-directions"><div className="container"><SectionTitle centered eyebrow="FIND YOUR DIRECTION" title="从一块开发板，走向更大的世界。" description="围绕嵌入式、物联网、电子设计、边缘智能与竞赛实践，把零散知识连成真正运行的系统。"/><Directions compact/></div></section>
  <section className="section section--white"><div className="container"><SectionTitle eyebrow="REAL PROJECTS" title="让想法，成为看得见的作品。" description="从前期健康监测，到 AIoT，再到多模态协同系统，项目在一次次实践里持续演进。" to="/projects" action="探索项目"/><div className="project-grid">{projects.map(p => <ProjectCard key={p.id} project={p}/>)}</div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="LIFE IN THE ASSOCIATION" title="培训、纳新，也有一起解决问题的日常。" description="这里记录协会真实开展过的活动与训练。" to="/activities" action="查看活动"/><div className="activity-grid">{activities.map(a => <ActivityCard key={a.id} activity={a}/>)}</div></div></section>
  <section className="home-manifesto"><div className="container"><span>01 / OUR BELIEF</span><h2>好的想法，<span>值得被做出来。</span></h2><p>保持好奇，认真动手。把经验分享给下一位同行的人。</p><Link className="text-link" to="/about">认识我们的协会<Icon name="arrow" size={18}/></Link></div><svg viewBox="0 0 1440 160" preserveAspectRatio="none" aria-hidden="true"><path d="M0 95Q200 0 420 100T900 105T1440 60V160H0Z" fill="#143145"/><path d="M0 110Q240 30 460 117T960 118T1440 90" fill="none" stroke="#4c96b6" opacity=".45"/></svg></section><JoinBanner/>
</>; }
