import { site, faq } from '../content';
import { Icon } from '../components/Icon';
import { SectionTitle } from '../components/UI';
export default function Join() { return <>
  <section className="join-hero"><div className="container"><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h1>带上好奇心，<br/><span>把第一步留给我们一起。</span></h1><p>不必已经是高手。愿意学习、认真动手、乐于分享，<br className="desktop-only"/>就是一个很好的开始。</p><a href="#recruitment" className="button button--primary">了解如何加入<Icon name="arrow" size={18}/></a><div className="join-orbit" aria-hidden="true"><span/><span/><div><Icon name="cpu" size={56}/></div><i><Icon name="wifi" size={27}/></i><b><Icon name="spark" size={24}/></b></div></div></section>
  <section className="section"><div className="container"><SectionTitle centered eyebrow="ROOM TO LEARN. SPACE TO BUILD." title="在这里，找到让自己成长的方式。"/><div className="benefit-grid">{[{icon:'book',title:'从零开始，也有方向',text:'从基础任务出发，把零散知识慢慢连成体系。'},{icon:'circuit',title:'不只听懂，更要做出',text:'让每一次学习，都有一个可以动手验证的结果。'},{icon:'users',title:'遇见愿意一起做事的人',text:'在交流与协作中，找到自己的专长，也认识新的可能。'}].map(x => <article key={x.title}><span><Icon name={x.icon} size={31}/></span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section>
  <section className="section section--white" id="recruitment"><div className="container"><SectionTitle eyebrow="FOUR SMALL STEPS" title="从了解，到一起做事。" description="以下为参考流程，具体安排以正式招新通知为准。"/><ol className="join-steps">{[{title:'了解协会',text:'看看方向、项目与学习资源。'},{title:'填写报名',text:'正式入口开放后提交意向。'},{title:'认识彼此',text:'交流兴趣、想法与学习计划。'},{title:'开始实践',text:'找到一个小任务，亲手完成它。'}].map((s,i) => <li key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></li>)}</ol><div className="recruitment-box"><div><h2>下一段旅程，期待与你一起。</h2><p>{site.recruitmentUrl ? '报名入口已开放，请查看正式招新说明。' : '正式招新时间与入口确认后将在这里公布。当前不采集任何报名信息。'}</p></div>{site.recruitmentUrl ? <a className="button button--primary" href={site.recruitmentUrl} target="_blank" rel="noopener noreferrer">立即报名<Icon name="external" size={18}/></a> : <button className="button button--disabled" disabled>招新入口暂未开放</button>}</div></div></section>
  <section className="section"><div className="container faq-grid"><SectionTitle eyebrow="GOOD QUESTIONS" title={<>开始之前，<br/>你也许想知道。</>}/><div className="faq-list">{faq.map(q => <details key={q.question}><summary>{q.question}<Icon name="plus" size={19}/></summary><p>{q.answer}</p></details>)}</div></div></section>
</>; }
