import { site, faq } from '../content';
import { Icon } from '../components/Icon';
import { SectionTitle } from '../components/UI';
export default function Join() { return <>
  <section className="join-hero"><div className="container"><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h1>带上好奇心，<br/><span>来实训楼 501 做点真的。</span></h1><p>{site.name}成立于 {site.founded} 年，隶属于{site.college}。<br className="desktop-only"/>不必已经是高手，愿意学习、认真动手、乐于分享，就是一个很好的开始。</p><a href="#recruitment" className="button button--primary">了解如何加入<Icon name="arrow" size={18}/></a><div className="join-orbit" aria-hidden="true"><span/><span/><div><Icon name="cpu" size={56}/></div><i><Icon name="wifi" size={27}/></i><b><Icon name="spark" size={24}/></b></div></div></section>
  <section className="section"><div className="container"><SectionTitle centered eyebrow="ROOM TO LEARN. SPACE TO BUILD." title="在这里，找到让自己成长的方式。"/><div className="benefit-grid">{[{icon:'book',title:'从基础资料开始',text:'从单片机、常用外设和开发工具出发，逐步建立工程基础。'},{icon:'circuit',title:'不只听懂，更要做出',text:'培训之后继续用代码、硬件、调试和竞赛把知识真正接起来。'},{icon:'users',title:'和愿意做事的人一起',text:'项目、训练和活动都需要协作，在实践里找到自己的方向。'}].map(x => <article key={x.title}><span><Icon name={x.icon} size={31}/></span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section>
  <section className="section section--white" id="recruitment"><div className="container"><SectionTitle eyebrow="HOW TO JOIN" title="从了解，到一起做事。" description="当前尚未建立新的纳新群，后续群聊和报名入口确认后会在这里更新。"/><ol className="join-steps">{[{title:'了解协会',text:'先看看方向、项目、活动与学习资源。'},{title:'联系负责人',text:'现阶段可以联系协会负责人了解情况。'},{title:'认识方向',text:'交流兴趣、基础与想尝试的技术方向。'},{title:'开始实践',text:'从一个能完成的小任务开始真正动手。'}].map((s,i) => <li key={s.title}><span>0{i+1}</span><h3>{s.title}</h3><p>{s.text}</p></li>)}</ol><div className="recruitment-box"><div><h2>{site.location}，欢迎来认识我们。</h2><p>当前尚未建立新的纳新群。需要了解协会时，可联系协会负责人；后续纳新群与报名入口会在官网同步更新。</p></div><button className="button button--disabled" disabled>纳新群筹备中</button></div></div></section>
  <section className="section"><div className="container faq-grid"><SectionTitle eyebrow="GOOD QUESTIONS" title={<>开始之前，<br/>你也许想知道。</>}/><div className="faq-list">{faq.map(q => <details key={q.question}><summary>{q.question}<Icon name="plus" size={19}/></summary><p>{q.answer}</p></details>)}</div></div></section>
</>; }
