import { useState } from 'react';
import { resources } from '../content';
import { Icon } from '../components/Icon';
import { EmptyState, FilterTabs, SearchField } from '../components/UI';
const categories = ['全部','单片机','嵌入式','物联网','人工智能','开发工具'];
export default function Resources() {
  const requested = new URLSearchParams(window.location.search).get('category') || '全部';
  const [category,setCategory] = useState(categories.includes(requested) ? requested : '全部');
  const [query,setQuery] = useState('');
  const list = resources.filter(r => (category === '全部' || r.category === category) && `${r.name} ${r.description} ${r.tags.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="page-dark resources-page"><section className="collection-header"><div className="container"><div className="resource-heading"><div><span className="eyebrow">START SMALL. KEEP BUILDING.</span><h1>给好奇心，<br/><span>一条清晰的起跑线。</span></h1><p>从官方文档和基础工具开始，找到下一步值得动手的事。</p></div><div className="resource-stack" aria-hidden="true"><span/><span/><span><Icon name="book" size={49}/></span></div></div><div className="learning-path"><span><Icon name="cpu" size={18}/>认识硬件</span><Icon name="chevron" size={15}/><span><Icon name="circuit" size={18}/>写下代码</span><Icon name="chevron" size={15}/><span><Icon name="wifi" size={18}/>连接系统</span><Icon name="chevron" size={15}/><span><Icon name="spark" size={18}/>实现想法</span></div><div className="collection-toolbar"><FilterTabs items={categories} value={category} onChange={setCategory}/><SearchField value={query} onChange={setQuery} placeholder="搜索学习资源…"/></div></div></section><section className="collection-results"><div className="container"><p className="results-count" aria-live="polite">{list.length} 项学习资源 · 打开官方文档</p>{list.length ? <div className="resource-grid">{list.map(r => <a key={r.id} className="resource-card" href={r.url} target="_blank" rel="noopener noreferrer"><div className="resource-card__top"><span className="resource-icon"><Icon name={r.category === '人工智能' ? 'spark' : r.category === '物联网' ? 'wifi' : r.category === '开发工具' ? 'layers' : 'cpu'}/></span><Icon name="external" size={17}/></div><h2>{r.name}</h2><p>{r.description}</p><div className="resource-card__bottom"><span className="tag">{r.level}</span><span>{r.publisher}</span></div></a>)}</div> : <EmptyState reset={() => {setCategory('全部');setQuery('');}}/>}<p className="quiet-note">资源链接指向公开文档；外部网站的内容与可访问性由其维护方负责。</p></div></section></div>;
}
