import { useState } from 'react';
import { resources } from '../content';
import { Icon } from '../components/Icon';
import { EmptyState, FilterTabs, SearchField } from '../components/UI';
const categories = ['全部','单片机','嵌入式','物联网','人工智能','开发工具'];
export default function Resources() {
  const requested = new URLSearchParams(window.location.search).get('category') || '全部';
  const [category,setCategory] = useState(categories.includes(requested) ? requested : '全部');
  const [query,setQuery] = useState('');
  const list = resources.filter(r => (category === '全部' || r.category === category) && `${r.name} ${r.description} ${r.tags.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div className="page-dark resources-page"><section className="collection-header"><div className="container"><div className="resource-heading"><div><span className="eyebrow">START SMALL. KEEP BUILDING.</span><h1>协会自己的学习路线，<br/><span>再配上可靠的官方文档。</span></h1><p>单片机学习笔记与蓝桥杯基础训练资料正在整理公开版；现阶段先保留清晰路线与官方参考。</p></div><div className="resource-stack" aria-hidden="true"><span/><span/><span><Icon name="book" size={49}/></span></div></div><div className="learning-path"><span><Icon name="cpu" size={18}/>51 / CT107D</span><Icon name="chevron" size={15}/><span><Icon name="circuit" size={18}/>中断 / 定时器 / 串口</span><Icon name="chevron" size={15}/><span><Icon name="wifi" size={18}/>STM32 / ESP32</span><Icon name="chevron" size={15}/><span><Icon name="spark" size={18}/>项目 / 竞赛</span></div><div className="collection-toolbar"><FilterTabs items={categories} value={category} onChange={setCategory}/><SearchField value={query} onChange={setQuery} placeholder="搜索学习资源…"/></div></div></section><section className="collection-results"><div className="container"><p className="results-count" aria-live="polite">{list.length} 项学习资源</p>{list.length ? <div className="resource-grid">{list.map(r => <a key={r.id} className="resource-card" href={r.url} target="_blank" rel="noopener noreferrer"><div className="resource-card__top"><span className="resource-icon"><Icon name={r.category === '人工智能' ? 'spark' : r.category === '物联网' ? 'wifi' : r.category === '开发工具' ? 'layers' : 'cpu'}/></span><Icon name="external" size={17}/></div><h2>{r.name}</h2><p>{r.description}</p><div className="resource-card__bottom"><span className="tag">{r.level}</span><span>{r.publisher}</span></div></a>)}</div> : <EmptyState reset={() => {setCategory('全部');setQuery('');}}/>}<p className="quiet-note">协会自编教程与清理后的 PDF 下载版会逐步开放；当前外部链接优先指向官方文档。</p></div></section></div>;
}
