import type { ReactNode } from 'react';
import { Icon } from './Icon';
import { Link } from '../lib/router';
import { directions } from '../content';
export function SectionTitle({ eyebrow, title, description, to, action = '了解更多', centered = false }: { eyebrow?: string; title: ReactNode; description?: string; to?: string; action?: string; centered?: boolean }) {
  return <div className={`section-heading ${centered ? 'section-heading--center' : ''}`}><div>{eyebrow && <span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{description && <p>{description}</p>}</div>{to && <Link to={to} className="text-link">{action}<Icon name="arrow" size={17}/></Link>}</div>;
}
export function ExampleNote({ children = '当前为视觉预览，以下内容为展示示例，不代表已核实的协会记录。' }: { children?: ReactNode }) { return <p className="example-note"><span className="example-dot"/>{children}</p>; }
export function Directions({ compact = false }: { compact?: boolean }) { return <div className={`directions-grid ${compact ? 'directions-grid--compact' : ''}`}>{directions.map(d => <Link to={`/resources?category=${encodeURIComponent(d.name === '嵌入式开发' ? '嵌入式' : d.name === '边缘智能' ? '人工智能' : d.name === '物联网' ? '物联网' : '全部')}`} className="direction-card" key={d.id}><span className="direction-icon"><Icon name={d.icon} size={29}/></span><h3>{d.name}</h3><p>{d.tags}</p>{!compact && <span className="direction-detail">{d.description}</span>}</Link>)}</div>; }
export function FilterTabs({ items, value, onChange, label = '分类筛选' }: { items: string[]; value: string; onChange: (value: string) => void; label?: string }) { return <div className="filter-tabs" aria-label={label} role="group">{items.map(item => <button key={item} type="button" className={value === item ? 'is-active' : ''} aria-pressed={value === item} onClick={() => onChange(item)}>{item}</button>)}</div>; }
export function SearchField({ value, onChange, placeholder = '搜索项目或技术…' }: { value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="search-field"><Icon name="search" size={18}/><span className="sr-only">{placeholder}</span><input type="search" value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}/>{value && <button type="button" aria-label="清空搜索" onClick={() => onChange('')}><Icon name="close" size={15}/></button>}</label>; }
export function EmptyState({ reset }: { reset?: () => void }) { return <div className="empty-state" role="status"><Icon name="search" size={35}/><h2>还没有匹配的内容</h2><p>换个关键词，或者看看其他分类。</p>{reset && <button className="button button--outline" onClick={reset}>查看全部内容</button>}</div>; }
export function JoinBanner() { return <section className="join-banner"><div className="container join-banner__inner"><div><span className="eyebrow">LET’S BUILD SOMETHING REAL</span><h2>下一件作品，<br className="mobile-only"/>从你的想法开始。</h2><p>不必等准备好了才出发。带上好奇心，和我们一起动手。</p></div><Link className="button button--primary" to="/join">加入我们<Icon name="arrow" size={18}/></Link></div></section>; }
