export const siteConfig = { name:'单片机与嵌入式技术协会', shortName:'ME Tech Lab', school:'哈尔滨理工大学', description:'从一行代码，到真实世界。面向学生的嵌入式实践与开源社区。', email:'me-tech@example.com', github:'https://github.com/', recruitmentUrl:'' };
export const stats = [{value:'2018',label:'成立年份'},{value:'128+',label:'在册成员'},{value:'16',label:'国家级奖项'},{value:'24',label:'开源项目'}];
export type Project = {slug:string; name:string; en:string; summary:string; status:string; year:string; tags:string[]; image:string; lead:string; contest:string; background:string; goal:string; architecture:string; result:string; members:string[]};
export const projects:Project[] = [
 {slug:'esp32-homepilot',name:'HomePilot 智能家居终端',en:'ESP32 / HomePilot',summary:'用一块 ESP32，把传感器、屏幕和家里的日常连接起来。',status:'持续迭代',year:'2026',tags:['ESP32','MQTT','LVGL'],image:'https://images.unsplash.com/photo-1558008258-3256797b43f3?auto=format&fit=crop&w=1200&q=80',lead:'林沐',contest:'校级创新实践项目',background:'宿舍和实验室里常见的设备彼此孤立，数据无法被简单地看见和控制。',goal:'打造一个可扩展、低功耗、开源的桌面智能终端。',architecture:'ESP32-S3 采集传感器数据，经 Wi-Fi / MQTT 送入本地网关，LVGL 提供交互。',result:'完成首版硬件打样，接入温湿度、光照与空气质量三类传感器。',members:['林沐','周思远','陈一']},
 {slug:'stm32-control',name:'STM32 智能控制系统',en:'STM32 / Control',summary:'从电机控制到状态监测，做一个真正能跑起来的控制系统。',status:'已结题',year:'2025',tags:['STM32','FreeRTOS','CAN'],image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',lead:'赵启航',contest:'全国大学生电子设计竞赛',background:'复杂设备需要稳定的控制、清晰的状态反馈以及可诊断的通信链路。',goal:'构建模块化控制平台，验证实时任务、总线通信与安全策略。',architecture:'STM32H743 主控 + FreeRTOS 任务调度 + CAN 总线 + 编码器闭环。',result:'完成两轴平台控制，关键任务抖动小于 20μs，获省级一等奖。',members:['赵启航','方可','王景钰']},
 {slug:'edge-vision',name:'EdgeSight 边缘视觉平台',en:'AIoT / EdgeSight',summary:'让模型离开云端，在一块小板上完成识别、决策和反馈。',status:'公开测试',year:'2026',tags:['YOLO','RK3588','OpenCV'],image:'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=1200&q=80',lead:'苏禾',contest:'机器人与人工智能创新赛',background:'许多校园场景需要实时响应，网络延迟和隐私要求让云端推理并不理想。',goal:'探索轻量视觉模型在边缘设备上的完整部署链路。',architecture:'摄像头采集 → ONNX Runtime / RKNN 推理 → 规则引擎 → 执行器反馈。',result:'在 Orange Pi 5 Pro 上实现 18 FPS 的目标识别演示。',members:['苏禾','陆知行','张然']}
];
export const awards = [{year:'2026',level:'国家级',title:'全国大学生电子设计竞赛',project:'智能控制系统',people:'赵启航 / 方可',date:'2026.08'},{year:'2026',level:'省级',title:'机器人与人工智能创新赛',project:'EdgeSight 边缘视觉平台',people:'苏禾 / 陆知行',date:'2026.06'},{year:'2025',level:'校级',title:'校园创新实践项目',project:'HomePilot 智能家居终端',people:'林沐 / 周思远',date:'2025.12'},{year:'2024',level:'国家级',title:'蓝桥杯全国软件和信息技术专业人才大赛',project:'嵌入式设计与开发',people:'协会代表队',date:'2024.05'}];
export const activities = [{title:'从 0 到 1：STM32 入门工作坊',date:'2026.03.22',tag:'技术培训',summary:'从点亮第一颗 LED 开始，完成一个按键控制的小系统。',image:'https://images.unsplash.com/photo-1531297484001-80022131f5a1?auto=format&fit=crop&w=900&q=80'},{title:'焊接与硬件调试夜',date:'2026.04.08',tag:'动手实践',summary:'认识常见元器件，学会看原理图、焊接和排查虚焊。',image:'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=900&q=80'},{title:'学长学姐的比赛复盘',date:'2026.05.16',tag:'经验分享',summary:'把赛场上的选择、失误和经验，讲给下一届队友听。',image:'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=900&q=80'}];
export const members = [{name:'高老师',role:'指导教师',focus:'嵌入式系统 / 教学实践',bio:'关注学生工程能力的成长，支持协会把想法做成作品。',avatar:'高'},{name:'赵启航',role:'协会负责人',focus:'STM32 / 实时系统',bio:'喜欢把复杂系统拆成可以验证的模块。',avatar:'赵'},{name:'苏禾',role:'项目负责人',focus:'边缘 AI / 机器人',bio:'在寻找模型准确率和设备功耗之间的平衡。',avatar:'苏'},{name:'林沐',role:'核心成员',focus:'ESP32 / 物联网',bio:'负责把传感器数据变成每个人都看得懂的界面。',avatar:'林'},{name:'周思远',role:'核心成员',focus:'PCB / 硬件设计',bio:'热衷于画板子，也热衷于把板子一次点亮。',avatar:'周'}];
export const resources = [{cat:'单片机',items:[['C 语言基础','从变量、指针到模块化编程，给硬件开发打底。','入门'],['STM32 官方文档','查找芯片手册、参考手册与 HAL 驱动说明。','进阶'],['ESP32 技术参考','了解 Wi-Fi、BLE 与 FreeRTOS 的完整能力。','进阶']]},{cat:'嵌入式',items:[['FreeRTOS','理解任务、队列、信号量，写出可维护的实时程序。','进阶'],['Linux & CMake','在真实的开发环境里构建、调试和交付。','进阶']]},{cat:'物联网',items:[['MQTT','轻量、可靠，适合设备间传递状态和指令。','入门'],['BLE / Wi-Fi','从无线连接开始理解设备如何进入网络。','入门']]},{cat:'AI',items:[['OpenCV','从图像读取到特征处理，建立视觉直觉。','入门'],['YOLO & ONNX','把模型部署到边缘设备，感受推理的全过程。','进阶']]}];
